LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_IS_RUNTIME_RESOURCE_OVERLAY := true
LOCAL_CERTIFICATE := platform
LOCAL_PACKAGE_NAME := PowerOffAlarmRes
LOCAL_SDK_VERSION := current
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/overlay/$(LOCAL_PACKAGE_NAME)
include $(BUILD_PACKAGE)
