LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := Etar
LOCAL_MODULE_CLASS := APPS
LOCAL_PRODUCT_MODULE := true
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_SRC_FILES := ws.xsoh.etar_34.apk

LOCAL_OVERRIDES_PACKAGES := Calendar

include $(BUILD_PREBUILT)
